FROM python:3.10-slim-buster

#Inside Container
# make a new folder inside container
WORKDIR /backend-flask

# outside Contaner -> Inside Container
# this contains the libraries want to instal to run the app
COPY requirements.txt requirements.txt

# Inside Container
# Install the python libraries used for the app
RUN pip3 install -r requirements.txt

#Outside Container -> Inside Container
# . means everything in the current directory
# first period . - /backend-flask (outside the container)
# second period . /backend-flask (inside container)
COPY . .

# Set environmentsl variables (Env Vars)
#Inside container and will remain set when the container is running
ENV FLASK_ENV=development

EXPOSE ${PORT}

# CMD (Command)
# python3 -m flask run --host=0.0.0.0 --port=4567
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=4567"]